name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - next
      - rc
  workflow_dispatch:

jobs:
  test:
    name: Test / OS ${{ matrix.os }} / Node ${{ matrix.node }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['18', '20']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Run tests
        run: |
          npm t
